-- Generated by tools/face-calib/gen.py (Calib F2 Colour b1, kit build 1). Don't edit.
-- Every test runs in pcall and then draws a status square: green = the call returned, pink = it
-- raised an error. A test that returns can still draw nothing or draw garbage: the photo decides.
local lvgl = require("lvgl")
local DIR = SCRIPT_PATH or "/"
local root = lvgl.Object(nil, { w = lvgl.HOR_RES(), h = lvgl.VER_RES(), bg_opa = lvgl.OPA(0), border_width = 0, pad_all = 0 })
root:clear_flag(lvgl.FLAG.SCROLLABLE)
root:clear_flag(lvgl.FLAG.CLICKABLE)
local function img(src, x, y)
  local o = root:Image { src = DIR .. src }
  o:set { x = x, y = y }
  return o
end
local function status(x, y, ok)
  img(ok and "st_ok.png" or "st_err.png", x, y)
end
local function try(x, y, fn)
  local ok = pcall(fn)
  status(x, y, ok)
  return ok
end
-- n digit cells from x (pitch 16), leading zeros; returns a setter and the first cell
local function counter(n, x, y)
  local cells = {}
  for i = 0, n - 1 do cells[i] = img("dg0.png", x + i * 16, y) end
  local function set(v)
    v = v // 1
    for i = n - 1, 0, -1 do
      cells[i]:set { src = DIR .. "dg" .. (v % 10) .. ".png" }
      v = v // 10
    end
  end
  return set, cells
end

status(29, 318, true)  -- alive
try(176, 318, function()  -- object_fill
  root:Object { x = 29, y = 158, w = 10, h = 34, bg_color = "#000000", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 41, y = 158, w = 10, h = 34, bg_color = "#080808", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 53, y = 158, w = 10, h = 34, bg_color = "#101010", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 65, y = 158, w = 10, h = 34, bg_color = "#181818", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 77, y = 158, w = 10, h = 34, bg_color = "#202020", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 89, y = 158, w = 10, h = 34, bg_color = "#282828", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 101, y = 158, w = 10, h = 34, bg_color = "#303030", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 113, y = 158, w = 10, h = 34, bg_color = "#383838", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 125, y = 158, w = 10, h = 34, bg_color = "#404040", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 137, y = 158, w = 10, h = 34, bg_color = "#484848", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 149, y = 158, w = 10, h = 34, bg_color = "#505050", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 161, y = 158, w = 10, h = 34, bg_color = "#585858", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 173, y = 158, w = 10, h = 34, bg_color = "#606060", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
end)
