-- Generated by tools/face-calib/gen.py (Calib F6 Lua b1, kit build 1). Don't edit.
-- Every test runs in pcall and then draws a status square: green = the call returned, pink = it
-- raised an error. A test that returns can still draw nothing or draw garbage: the photo decides.
local lvgl = require("lvgl")
local DIR = SCRIPT_PATH or "/"
local root = lvgl.Object(nil, { w = lvgl.HOR_RES(), h = lvgl.VER_RES(), bg_opa = lvgl.OPA(0), border_width = 0, pad_all = 0 })
root:clear_flag(lvgl.FLAG.SCROLLABLE)
root:clear_flag(lvgl.FLAG.CLICKABLE)
local function img(src, x, y)
  local o = root:Image { src = DIR .. src }
  o:set { x = x, y = y }
  return o
end
local function status(x, y, ok)
  img(ok and "st_ok.png" or "st_err.png", x, y)
end
local function try(x, y, fn)
  local ok = pcall(fn)
  status(x, y, ok)
  return ok
end
-- n digit cells from x (pitch 16), leading zeros; returns a setter and the first cell
local function counter(n, x, y)
  local cells = {}
  for i = 0, n - 1 do cells[i] = img("dg0.png", x + i * 16, y) end
  local function set(v)
    v = v // 1
    for i = n - 1, 0, -1 do
      cells[i]:set { src = DIR .. "dg" .. (v % 10) .. ".png" }
      v = v // 10
    end
  end
  return set, cells
end

status(242, 58, true)  -- alive
try(242, 83, function() local o = img("target.png", 172, 70) end)  -- place_0
try(242, 127, function() local o = img("target.png", 92, 114) end)  -- place_1
try(242, 162, function() local set = counter(3, 92, 158); set(lvgl.HOR_RES()) end)  -- hor_res
try(242, 178, function() local set = counter(3, 172, 158); set(lvgl.VER_RES()) end)  -- ver_res
try(242, 206, function()  -- lua_hour
  local dataman = require("dataman")
  local set, cells = counter(2, 92, 202)
  local t = { hh = 0, hl = 0 }
  dataman.subscribe("timeHourHigh", cells[0], function(_, v) t.hh = v // 256; set(t.hh * 10 + t.hl) end)
  dataman.subscribe("timeHourLow", cells[1], function(_, v) t.hl = v // 256; set(t.hh * 10 + t.hl) end)
end)
try(242, 222, function()  -- lua_minute
  local dataman = require("dataman")
  local set, cells = counter(2, 128, 202)
  local t = { mh = 0, ml = 0 }
  dataman.subscribe("timeMinuteHigh", cells[0], function(_, v) t.mh = v // 256; set(t.mh * 10 + t.ml) end)
  dataman.subscribe("timeMinuteLow", cells[1], function(_, v) t.ml = v // 256; set(t.mh * 10 + t.ml) end)
end)
try(242, 259, function()  -- raw_minute_low: the raw dataman value (no // 256)
  local dataman = require("dataman")
  local set, cells = counter(6, 92, 246)
  dataman.subscribe("timeMinuteLow", cells[5], function(_, v) set(v) end)
end)
try(242, 294, function() root:Label { text = "LUA 0123", x = 92, y = 290, text_color = "#ffffff" } end)  -- label
try(242, 320, function()  -- object_fill
  root:Object { x = 92, y = 320, w = 24, h = 16, bg_color = "#ffffff", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 120, y = 320, w = 24, h = 16, bg_color = "#808080", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
  root:Object { x = 148, y = 320, w = 24, h = 16, bg_color = "#404040", bg_opa = lvgl.OPA(100), border_width = 0, radius = 0, pad_all = 0 }
end)
try(242, 330, function()  -- timer: the square blinks once a second if Lua timers run
  local sq = img("st_ok.png", 188, 325)
  local on = true
  lvgl.Timer { period = 1000, cb = function(t)
    on = not on
    if on then sq:clear_flag(lvgl.FLAG.HIDDEN) else sq:add_flag(lvgl.FLAG.HIDDEN) end
  end }
end)
