-- Generated by tools/face-calib/gen.py (Calib F3 Images b1, kit build 1). Don't edit.
-- Every test runs in pcall and then draws a status square: green = the call returned, pink = it
-- raised an error. A test that returns can still draw nothing or draw garbage: the photo decides.
local lvgl = require("lvgl")
local DIR = SCRIPT_PATH or "/"
local root = lvgl.Object(nil, { w = lvgl.HOR_RES(), h = lvgl.VER_RES(), bg_opa = lvgl.OPA(0), border_width = 0, pad_all = 0 })
root:clear_flag(lvgl.FLAG.SCROLLABLE)
root:clear_flag(lvgl.FLAG.CLICKABLE)
local function img(src, x, y)
  local o = root:Image { src = DIR .. src }
  o:set { x = x, y = y }
  return o
end
local function status(x, y, ok)
  img(ok and "st_ok.png" or "st_err.png", x, y)
end
local function try(x, y, fn)
  local ok = pcall(fn)
  status(x, y, ok)
  return ok
end
-- n digit cells from x (pitch 16), leading zeros; returns a setter and the first cell
local function counter(n, x, y)
  local cells = {}
  for i = 0, n - 1 do cells[i] = img("dg0.png", x + i * 16, y) end
  local function set(v)
    v = v // 1
    for i = n - 1, 0, -1 do
      cells[i]:set { src = DIR .. "dg" .. (v % 10) .. ".png" }
      v = v // 10
    end
  end
  return set, cells
end

status(176, 310, true)  -- alive
try(43, 176, function() local o = img("t_png_rgba.png", 30, 140) end)  -- image_png_rgba
try(83, 176, function() local o = img("t_png8.png", 70, 140) end)  -- image_png8
try(123, 176, function() local o = img("t_png_grey.png", 110, 140) end)  -- image_png_grey
try(163, 176, function() local o = img("t_png_rgb.png", 150, 140) end)  -- image_png_rgb
try(43, 226, function() local o = img("t_v8_tca32.bin", 30, 190) end)  -- image_v8_tca32
try(83, 226, function() local o = img("t_v8_tca16.bin", 70, 190) end)  -- image_v8_tca16
try(123, 226, function() local o = img("t_v9_argb8888.bin", 110, 190) end)  -- image_v9_argb8888
try(163, 226, function() local o = img("t_v9_rgb565.bin", 150, 190) end)  -- image_v9_rgb565
try(59, 310, function() local o = img("t_png_rgba.png", 46, 256); o:set { zoom = 512 } end)  -- image_zoom
try(139, 310, function() local o = img("t_png_rgba.png", 126, 256); o:set { scale = 512 } end)  -- image_scale
