#!/usr/bin/env node
// Writes one self-contained ES module for a band app: the device profile's data plus the
// profile.js helpers, so band code can `import device from './device'` (the Vela bundler can't
// reach files outside the app's src/). Band apps regenerate it on every build (BART: `npm run
// device`, run by `prebuild`); --check fails when the file on disk is stale.
//
//   node tools/vela-calib/export.mjs band10pro apps/bart-watch/band/src/common/device.js
//   node tools/vela-calib/export.mjs band10pro apps/bart-watch/band/src/common/device.js --check
//
// The profile is devices/<device-id>/profile.json. Band apps are quick apps, so only the
// top-level facts and the `quickapp` section are exported (the `face` section is dropped).
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { profilePath } from './profile-node.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const args = process.argv.slice(2)
const check = args.includes('--check')
const [id, dest] = args.filter((a) => a !== '--check')
if (!id || !dest) {
  console.error('usage: node export.mjs <device-id> <dest.js> [--check]')
  process.exit(2)
}
const file = profilePath(id)
const data = JSON.parse(fs.readFileSync(file, 'utf8'))
// Band code only needs the facts; drop provenance detail, the compiler's CSS list and the face
// section to keep it small.
const strip = (o, depth = 0) => {
  if (Array.isArray(o)) return o
  if (!o || typeof o !== 'object') return o
  const out = {}
  for (const [k, v] of Object.entries(o)) {
    if (['detail', 'source', 'date', 'note', 'by_size_px', 'fit_error_em', 'what', 'lumas', 'about'].includes(k)) continue
    if (k === 'compiler_accepts') continue
    if (depth === 0 && k === 'face') continue
    out[k] = strip(v, depth + 1)
  }
  return out
}
const lib = fs.readFileSync(path.join(HERE, 'profile.js'), 'utf8').replace(/\nexport default makeProfile\n?$/, '\n')
const rel = path.relative(path.resolve(HERE, '..', '..'), file)
const fw = data.firmware && typeof data.firmware === 'object' ? data.firmware.version : data.firmware
const src = `// GENERATED by tools/vela-calib/export.mjs from ${rel} (updated ${data.updated}, firmware ${fw}). Do not edit.
${lib}
const DATA = ${JSON.stringify(strip(data))}

const device = makeProfile(DATA)
export default device
`
if (check) {
  const have = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : ''
  if (have !== src) {
    console.error(`${dest} is stale: regenerate it from ${rel} (node tools/vela-calib/export.mjs ${id} ${dest})`)
    process.exit(1)
  }
  console.log(`${dest}: matches ${rel}`)
} else {
  fs.writeFileSync(dest, src)
  console.log(`${dest}: ${id} profile (${(src.length / 1024).toFixed(1)} KB)`)
}
