-- Generated by tools/face-calib/gen.py (Calib F8 AOD Lua b1, kit build 1). Don't edit.
-- Every test runs in pcall and then draws a status square: green = the call returned, pink = it
-- raised an error. A test that returns can still draw nothing or draw garbage: the photo decides.
local lvgl = require("lvgl")
local DIR = SCRIPT_PATH or "/"
local root = lvgl.Object(nil, { w = lvgl.HOR_RES(), h = lvgl.VER_RES(), bg_opa = lvgl.OPA(0), border_width = 0, pad_all = 0 })
root:clear_flag(lvgl.FLAG.SCROLLABLE)
root:clear_flag(lvgl.FLAG.CLICKABLE)
local function img(src, x, y)
  local o = root:Image { src = DIR .. src }
  o:set { x = x, y = y }
  return o
end
local function status(x, y, ok)
  img(ok and "st_ok.png" or "st_err.png", x, y)
end
local function try(x, y, fn)
  local ok = pcall(fn)
  status(x, y, ok)
  return ok
end
-- n digit cells from x (pitch 16), leading zeros; returns a setter and the first cell
local function counter(n, x, y)
  local cells = {}
  for i = 0, n - 1 do cells[i] = img("dg0.png", x + i * 16, y) end
  local function set(v)
    v = v // 1
    for i = n - 1, 0, -1 do
      cells[i]:set { src = DIR .. "dg" .. (v % 10) .. ".png" }
      v = v // 10
    end
  end
  return set, cells
end

try(176, 68, function() local o = img("sq_big.png", 110, 68) end)  -- lua_square
